blank_issues_enabled: false
contact_links:
  - name: Community Support for ShizuCallRecorder
    url: https://github.com/kitsumed/ShizuCallRecorder/discussions
    about: Please ask and answer other users questions here. THIS IS NOT FOR BUG REPORTS.
  - name: Community Support for Shizuku (thedjchi fork)
    url: https://github.com/thedjchi/Shizuku/discussions/categories/q-a
    about: Please ask and answer other users questions here. THIS IS NOT FOR BUG REPORTS.
