package com.accu.ui.theme

import androidx.compose.ui.graphics.Color

// Primary palette — deep space blue-violet
val md_theme_light_primary            = Color(0xFF4A56E2)
val md_theme_light_onPrimary          = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer   = Color(0xFFDEE0FF)
val md_theme_light_onPrimaryContainer = Color(0xFF00006E)
val md_theme_light_secondary          = Color(0xFF5D5C7D)
val md_theme_light_onSecondary        = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE2E0F9)
val md_theme_light_onSecondaryContainer= Color(0xFF191A37)
val md_theme_light_tertiary           = Color(0xFF7A527C)
val md_theme_light_onTertiary         = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer  = Color(0xFFFFD6FC)
val md_theme_light_onTertiaryContainer= Color(0xFF2E1034)
val md_theme_light_error              = Color(0xFFBA1A1A)
val md_theme_light_errorContainer     = Color(0xFFFFDAD6)
val md_theme_light_onError            = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer   = Color(0xFF410002)
val md_theme_light_background         = Color(0xFFFBFBFF)
val md_theme_light_onBackground       = Color(0xFF1B1B1F)
val md_theme_light_surface            = Color(0xFFFBFBFF)
val md_theme_light_onSurface          = Color(0xFF1B1B1F)
val md_theme_light_surfaceVariant     = Color(0xFFE4E1EC)
val md_theme_light_onSurfaceVariant   = Color(0xFF47464F)
val md_theme_light_outline            = Color(0xFF787680)
val md_theme_light_outlineVariant     = Color(0xFFC8C5D0)
val md_theme_light_scrim              = Color(0xFF000000)
val md_theme_light_inverseSurface     = Color(0xFF303034)
val md_theme_light_inverseOnSurface   = Color(0xFFF3EFF4)
val md_theme_light_inversePrimary     = Color(0xFFBAC3FF)
val md_theme_light_surfaceTint        = Color(0xFF4A56E2)

val md_theme_dark_primary             = Color(0xFFBAC3FF)
val md_theme_dark_onPrimary           = Color(0xFF0F15AA)
val md_theme_dark_primaryContainer    = Color(0xFF3038C8)
val md_theme_dark_onPrimaryContainer  = Color(0xFFDEE0FF)
val md_theme_dark_secondary           = Color(0xFFC5C4DD)
val md_theme_dark_onSecondary         = Color(0xFF2E2E4D)
val md_theme_dark_secondaryContainer  = Color(0xFF454565)
val md_theme_dark_onSecondaryContainer= Color(0xFFE2E0F9)
val md_theme_dark_tertiary            = Color(0xFFEDB8EF)
val md_theme_dark_onTertiary          = Color(0xFF47244A)
val md_theme_dark_tertiaryContainer   = Color(0xFF5F3A62)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD6FC)
val md_theme_dark_error               = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer      = Color(0xFF93000A)
val md_theme_dark_onError             = Color(0xFF690005)
val md_theme_dark_onErrorContainer    = Color(0xFFFFDAD6)
val md_theme_dark_background          = Color(0xFF131316)
val md_theme_dark_onBackground        = Color(0xFFE5E1E6)
val md_theme_dark_surface             = Color(0xFF131316)
val md_theme_dark_onSurface           = Color(0xFFE5E1E6)
val md_theme_dark_surfaceVariant      = Color(0xFF47464F)
val md_theme_dark_onSurfaceVariant    = Color(0xFFC8C5D0)
val md_theme_dark_outline             = Color(0xFF918F9A)
val md_theme_dark_outlineVariant      = Color(0xFF47464F)
val md_theme_dark_scrim               = Color(0xFF000000)
val md_theme_dark_inverseSurface      = Color(0xFFE5E1E6)
val md_theme_dark_inverseOnSurface    = Color(0xFF303034)
val md_theme_dark_inversePrimary      = Color(0xFF4A56E2)
val md_theme_dark_surfaceTint         = Color(0xFFBAC3FF)

// Accent colors used throughout the app
val AccentCyan    = Color(0xFF00D4FF)
val AccentGreen   = Color(0xFF00E676)
val AccentOrange  = Color(0xFFFF6D00)
val AccentRed     = Color(0xFFFF1744)
val AccentPurple  = Color(0xFFD500F9)
val AccentYellow  = Color(0xFFFFD600)
val SurfaceGlass  = Color(0x1AFFFFFF)
val SurfaceGlassDark = Color(0x1A000000)
